src/IRY/AppliBundle/Entity/Image.php
<?php

namespace IRY\AppliBundle\Entity;
use Doctrine\ORM\Mapping as ORM;

class Image {
    private $id;
    private $course;
    private $path;
    /**
     * @var string
     */
    private $name;

    /**
     * @var integer
     */
    private $theOrder = 1;
    protected $file;
    private $folder;
    const IMAGE_CM = "cm";
    const IMAGE_SCHEMA = "schema";

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set img
     *
     * @param string $img
     * @return Schema
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get img
     *
     * @return string 
     */
    public function getPath()
    {
        return $this->path;
    }


     /**
     * Set course
     *
     * @param string $course
     * @return Schema
     */
    public function setCourse($course)
    {
        $this->course = $course;

        return $this;
    }

    /**
     * Get course
     *
     * @return string 
     */
    public function getCourse()
    {
        return $this->course;
    }


    /**
     * Set name
     *
     * @param string $name
     * @return Image
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set theOrder
     *
     * @param integer $theOrder
     * @return Image
     */
    public function setTheOrder($theOrder)
    {
        $this->theOrder = $theOrder;

        return $this;
    }

    /**
     * Get theOrder
     *
     * @return integer 
     */
    public function getTheOrder()
    {
        return $this->theOrder;
    }
    public function getFile()
    {
        return $this->file;
    }

    public function setFile($file)
    {
        $this->file = $file;

        return $this;
    }
    public function preUpload()
    {   
        if (null !== $this->file) {
            // do whatever you want to generate a unique name
            $filename = $this->getFolder() . "/" . sha1(uniqid(mt_rand(), true));
            $this->path = $filename.'.'.$this->file->guessExtension();
        }
    }

    public function removeUpload()
    {
        if ($file = $this->getAbsolutePath()) {
            if (file_exists($file)) {
                unlink($file); 
            }
        }
    }

    public function upload()
    {
        // The file property can be empty if the field is not required
        if (null === $this->file) {
            return;
        }

        // Use the original file name here but you should
        // sanitize it at least to avoid any security issues

        // move takes the target directory and then the
        // target filename to move to
        $this->file->move(
            $this->getUploadRootDir(),
            $this->path
        );

        // Set the path property to the filename where you've saved the file
        //$this->path = $this->file->getClientOriginalName();

        // Clean up the file property as you won't need it anymore
        $this->file = null;
    }

    public function getAbsolutePath()
    {
        return null === $this->path
            ? null
            : $this->getUploadRootDir().$this->path;
    }

    public function getWebPath()
    {
        return null === $this->path
            ? null
            : $this->getUploadDir().$this->path;
    }

    protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        $reflClass = new \ReflectionClass(get_class($this));
        
        return dirname($reflClass->getFileName()).'/../../../../web/'.$this->getUploadDir().$this->getFolder();
    }

    protected function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw up.
        // when displaying uploaded doc/image in the view.
        return 'uploads/';
    }

    public function setFolder($folder)
    {
        $this->folder = $folder;

        return $this;
    }
    public function getFolder()
    {
        return $this->folder;
    }
}

src/IRY/AppliBundle/Entity/Pilot.php
<?php

namespace IRY\AppliBundle\Entity;
use Doctrine\ORM\Mapping as ORM;

class Pilot {
	private $id;
    private $name;
    private $isCalling;
    private $dateCalling;
    private $serie;
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $results;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->results = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Pilot
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Add results
     *
     * @param \IRY\AppliBundle\Entity\Result $results
     * @return Pilot
     */
    public function addResult(\IRY\AppliBundle\Entity\Result $results)
    {
        $this->results[] = $results;

        return $this;
    }

    /**
     * Remove results
     *
     * @param \IRY\AppliBundle\Entity\Result $results
     */
    public function removeResult(\IRY\AppliBundle\Entity\Result $results)
    {
        $this->results->removeElement($results);
    }

    /**
     * Get results
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getResults()
    {
        return $this->results;
    }

    public function getNbErrors()
    {
        $errors = 0;
        foreach ($this->getResults() as $result) {
            if ($result->getIsError() == true) {
                $errors++;
            }
        }

        return $errors;
    }
    public function getNbSuccess()
    {
        $success = 0;
        
        foreach ($this->getResults() as $result) {
            if ($result->getIsGlobal() == false && $result->getStep()->isLastStep() == true && $result->getIsError() == false) {
                $success++;
            }
        }

        return $success;
    }

    public function getCurrentStep()
    {
        $results = $this->getResults();
        if (count($results) > 0) {
            $lastResult = $results[count($results) - 1];
            $lastStep = $lastResult->getStep();

            return $lastStep->getNextStep();
        }

        return null;
    }

    /**
     * Set isCalling
     *
     * @param boolean $isCalling
     * @return Pilot
     */
    public function setIsCalling($isCalling = false)
    {
        $this->isCalling = $isCalling;

        return $this;
    }

    /**
     * Get isCalling
     *
     * @return boolean 
     */
    public function getIsCalling()
    {
        return $this->isCalling;
    }

    /**
     * Set dateCalling
     *
     * @param \DateTime $dateCalling
     * @return Pilot
     */
    public function setDateCalling($dateCalling)
    {
        $this->dateCalling = $dateCalling;

        return $this;
    }

    /**
     * Get dateCalling
     *
     * @return \DateTime 
     */
    public function getDateCalling()
    {
        return $this->dateCalling;
    }
    public function getJavascriptTimestampDateCalling()
    {
        if (is_null($this->getDateCalling()) == false) {
            return $this->dateCalling->getTimestamp() * 1000; // Because PHP counts the numbers of seconds, and JS the milliseconds
        }
        return 0;
    }

    /**
     * Set serie
     *
     * @param \IRY\AppliBundle\Entity\Serie $serie
     * @return Pilot
     */
    public function setSerie(\IRY\AppliBundle\Entity\Serie $serie = null)
    {
        $this->serie = $serie;

        return $this;
    }

    /**
     * Get serie
     *
     * @return \IRY\AppliBundle\Entity\Serie 
     */
    public function getSerie()
    {
        return $this->serie;
    }

    public function getResultsInCourse($course)
    {
        $resultsInCourse = new \Doctrine\Common\Collections\ArrayCollection();

        foreach ($this->getResults() as $result) {
            if ($result->getStep()->getCourse()->getId() == $course->getId()) {
                $resultsInCourse[] = $result;
            }
        }
        return $resultsInCourse;
    }
}

src/IRY/AppliBundle/Entity/Step.php
<?php

namespace IRY\AppliBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use IRY\AppliBundle\Entity\Pilot;

  /**
     * @var \IRY\AppliBundle\Entity\Step
     */
class Step {
    private $id;
    private $name;
    private $course;
    private $results;
    /**
     * @var integer
     */
    private $theOrder;
    /**
     * @var string
     */
    private $btn_name;

    /**
     * @var boolean
     */
    private $btn_state;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->results = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Step
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }


    /**
     * Add results
     *
     * @param \IRY\AppliBundle\Entity\Result $results
     * @return Step
     */
    public function addResult(\IRY\AppliBundle\Entity\Result $results)
    {
        $this->results[] = $results;

        return $this;
    }

    /**
     * Remove results
     *
     * @param \IRY\AppliBundle\Entity\Result $results
     */
    public function removeResult(\IRY\AppliBundle\Entity\Result $results)
    {
        $this->results->removeElement($results);
    }

    /**
     * Get results
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getResults()
    {
        return $this->results;
    }

    /**
     * Set course
     *
     * @param \IRY\AppliBundle\Entity\Course $course
     * @return Step
     */
    public function setCourse(\IRY\AppliBundle\Entity\Course $course = null)
    {
        $this->course = $course;

        return $this;
    }

    /**
     * Get course
     *
     * @return \IRY\AppliBundle\Entity\Course 
     */
    public function getCourse()
    {
        return $this->course;
    }

    // public function getNbEssai()
    // {
    //     $nbEssai = 0;
    //     $i = 0;
    //     for ($i;$this->isError;$i++)
    //     {
    //         $nbEssai = $nbEssai +1;
    //     }
    //     return $this->nbEssai;
    // }

    public function getNbErrors()
    {
        $nbErrors = 0;

        for ($i=0; $i < count($this->results); $i++) { 
            if ($this->results[$i]->getIsError() == true) {
                $nbErrors++;
            }
        }
             
        return $nbErrors;
    }

    public function getNbLocalErrors()
    {
        $nbErrors = 0;

        for ($i=0; $i < count($this->results); $i++) { 
            if ($this->results[$i]->getIsGlobal() == false && $this->results[$i]->getIsError() == true) {
                $nbErrors++;
            }
        }
             
        return $nbErrors;
    }

    public function getPercentNbLocalErrors()
    {
        $nbErrors = 0;
        $nbEssais = 0;

        for ($i=0; $i < count($this->results); $i++) { 
            if ($this->results[$i]->getIsGlobal() == false) {
                $nbEssais++;
                if ($this->results[$i]->getIsError() == true) {
                    $nbErrors++;
                }
            }
        }

        if ($nbEssais == 0) {
            return 0; // if we don't explicitely return 0, we will get an Exception, division by 0
        }
        
        return $nbErrors * 100 / $nbEssais;
    }


    /**
     * Set btn_name
     *
     * @param string $btnName
     * @return Step
     */
    public function setBtnName($btnName)
    {
        $this->btn_name = $btnName;

        return $this;
    }

    /**
     * Get btn_name
     *
     * @return string 
     */
    public function getBtnName()
    {
        return $this->btn_name;
    }

    /**
     * Set btn_state
     *
     * @param boolean $btnState
     * @return Step
     */
    public function setBtnState($btnState)
    {
        $this->btn_state = $btnState;

        return $this;
    }

    /**
     * Get btn_state
     *
     * @return boolean 
     */
    public function getBtnState()
    {
        return $this->btn_state;
    }

    public function isLastStep()
    {
        $lastStep = $this->course->getLastStep();

        if (is_null($lastStep) == false) {
            
            return $lastStep->getId() == $this->getId();
        }

        return false;
    }

    public function getNextStep()
    {
        $steps = $this->getCourse()->getSteps();

        $index = null;

        foreach ($steps as $i => $step) {
            if ($step->getId() == $this->getId()) {
                $index = $i;
                break;
            }
        }

        // return null if the step has not been found (bug) or if there is no next step.
        return (is_null($index) == true || $i >= count($steps) ) ? null : $steps[$i + 1];
    }

    public function getPercentInCourse()
    {
        $steps = $this->getCourse()->getSteps();
        $index = null;

        $foreachIndex = 0; // use this variable because the sorting doesn't affect the indexes.
        foreach ($steps as $step) {
            if ($step->getId() == $this->getId()) {
                $index = $foreachIndex;
                break;
            }
            $foreachIndex++;
        }

        $percent = 0;

        if (is_null($index) == false) {
            $index++; // Because an array starts from 0
            $percent = $index * 100 / count($steps);
        }

        return $percent;
    }
    public function getLastResultFromPilot(Pilot $pilot){
        $results = $this->getResults();
        foreach ($results as $result) {
            if ($result->getPilot()->getId() != $pilot->getId()) {
                $results->removeElement($result);
            }
        }
        return $results->last();
    }
    /**
     * Set theOrder
     *
     * @param integer $theOrder
     * @return Step
     */
    public function setTheOrder($theOrder)
    {
        $this->theOrder = $theOrder;

        return $this;
    }

    /**
     * Get theOrder
     *
     * @return integer 
     */
    public function getTheOrder()
    {
        return $this->theOrder;
    }
}

src/IRY/AppliBundle/Resources/views/Application/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta charset="UTF-8">
        <title>{% block title %}IRY{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="favicon.png" />
        <link href="{{ asset('bundles/iryappli/css/ie.css') }}" rel="stylesheet">
        <link href="{{ asset('bundles/iryappli/css/print.css') }}" rel="stylesheet">
        <link href="{{ asset('bundles/iryappli/css/screen.css') }}" rel="stylesheet">
        <link href="{{ asset('bundles/iryappli/css/custom.css') }}" rel="stylesheet">
        <link href="http://cdn.jsdelivr.net/select2/3.5.2/select2.css" rel="stylesheet">
        <link href="{{ asset('bundles/iryappli/css/slick.css') }}" rel="stylesheet">

        <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
        <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
        <script src="//cdn.jsdelivr.net/select2/3.5.2/select2.min.js"></script>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block header %}
            <header id="header" class="cf">
                <div id="header_left" class="left">
                    {% block header_back_btn %}{% endblock %}
                    <div id="logo">
                        <a href="{{path("iry_appli_home")}}">
                            <img src="{{ asset('bundles/iryappli') }}/img/logo.png" alt="Logo IRY">
                        </a>
                    </div>
                </div>
                <div id="header_right" class="right">
                    <a href="{{path('logout')}}" class="logout">Logout</a>
                </div>
                <div id="header_center" class="center">
                    <h1>{% block header_title %}{% endblock %}</h1>
                </div>

            </header>
        {% endblock %}
        {% block body %}{% endblock %}
        {% block footer %}{% endblock %}
        
        <script type="text/javascript" src="{{ asset('bundles/iryappli/libraries/jquery.cookies.js') }}"></script>
        <script type="text/javascript" src="{{ asset('bundles/iryappli/libraries/mustache.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('bundles/iryappli/js/script.js') }}"></script>
        <script type="text/javascript" src="{{ asset('bundles/iryappli/js/slick.min.js') }}"></script>

        </script>
        <script type="text/javascript">
            $(document).ready(function(){
                $('.cm_images').slick();
            });
        </script>
    </body>
</html>	

src/IRY/AppliBundle/Resources/views/Application/choixcours.html.twig
{% extends 'IRYAppliBundle:Application:base.html.twig' %}
{% block header_title %}
	{{helicopter.name}}
{% endblock %}
{% block header_back_btn %}
	<a href="{{ path('iry_appli_home') }}" id="back_btn">
		<img src="{{ asset('bundles/iryappli') }}/img/fleche_gauche.png" alt="Retour accueil">
	</a>
{% endblock %}
{% block body %}
    <div id="content">
      <div class="liste_categories_wrap">
        <div id="categories">
          <section class="category theme_section">
            <h2>Choose your System</h2>
            <div class="list">
              <ul>
		        {% for theme in helicopter.themes %} <!-- boucle parmi la liste des thèmes -->

	        		<li class="theme {{ (theme.subthemes|length == 0) ? "inactive" : "" }} {{ serie.hasAllCoursesOfTheme(theme) == true ? "saw" : "" }}" data-theme="{{theme.id}}" id="theme{{theme.id}}"><span>{{theme.name}}</span></li>
		        {% endfor %}
              </ul>
            </div>
          </section>
          <section class="category subtheme_section">
            <h2>Choose your Sub-system</h2>
            <div class="list">
              <ul>
			      {% for theme in helicopter.themes %} <!-- boucle parmi la liste des thèmes -->
			        {% for subtheme in theme.subthemes %} <!-- boucle parmi la liste des thèmes -->
		        		<li class="subtheme {{ (subtheme.courses|length == 0) ? "inactive" : "" }} {{ serie.hasAllCoursesOfSubTheme(subtheme) == true ? "saw" : "" }}" data-theme="{{theme.id}}" data-subtheme="{{subtheme.id}}" id="subtheme{{subtheme.id}}"><span>{{subtheme.name}}</span></li>
			        {% endfor %}
		        {% endfor %}
              </ul>
            </div>
          </section>
          <section class="category course_section">
            <h2>Choose your Chapter</h2>
            <div class="list">
              <ul>
	              {% for theme in helicopter.themes %} <!-- boucle parmi la liste des thèmes -->
		              {% for subtheme in theme.subthemes %} <!-- boucle parmi la liste des thèmes -->
                    {% for course in subtheme.courses %} <!-- boucle parmi la liste des thèmes -->
                      {% if (course.typeCourse.id == 1) %} {# cm #}
                        {% set url = path('iry_appli_cm', {'course_id': course.id}) %}
                      {% elseif (course.typeCourse.id == 2) %} {# cd #}
                        {% set url = path('iry_appli_cd', {'course_id': course.id}) %}
                      {% elseif (course.typeCourse.id == 3) %} {# vi #}
                        {% set url = path('iry_appli_vi', {'course_id': course.id}) %}
                      {% elseif (course.typeCourse.id == 4) %} {# ep #}
                        {% set url = path('iry_appli_ep', {'course_id': course.id}) %}      
                      {% endif %}
                      <a href="{{ url }}">
                        <li data-subtheme="{{subtheme.id}}" theme="{{theme.id}}" class="course course{{course.typeCourse.id}} {{ serie.hasCourse(course) == true ? "saw" : "" }}" id="course{{course.id}}"><span>{{course.name}}</span></li>
                        {# {{ serie.hasCourse(course) == true ? "saw" : "" }} #}
                      </a>
                    {% endfor %}
		              {% endfor %}
	              {% endfor %}
              </ul>
            </div>
          </section>
        </div>
      </div>
      <div id="legend">
        <div class="types_course">
          <div class="type_course cm">
              <span>Theoretical Course</span>
          </div>
          <div class="type_course cd">
              <span>Demonstrative Course</span>
          </div>
          <div class="type_course vi">
              <span>Immersive Movie</span>
          </div>
          <div class="type_course ep">
              <span>Practical Training</span>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

src/IRY/AppliBundle/Resources/views/Application/coursMagistral.html.twig
{% extends 'IRYAppliBundle:Application:base.html.twig' %}

{% block header_title %}
    {{course.name}}
{% endblock %}

{% block header_back_btn %}
    <a href="{{ path('iry_appli_choixcours', {helicopter_id: course.subTheme.theme.helicopter.id}) }}" id="back_btn">
        <img src="{{ asset('bundles/iryappli') }}/img/fleche_gauche.png" alt="Retour accueil">
    </a>
{% endblock %}

{% block body %}
    <div id="content">
        <div class="cm_images">
            {% for image in images %}
                <div class="image">
                    <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,18,0" width="600" height="400" id="fullscreen" align="middle">
                        <param name="allowFullScreen" value="true" />
                        <param name="movie" value="/{{image.webPath}}" />
                        <embed class="cm_embed" src="/{{image.webPath}}" allowFullScreen="true" name="fullscreen" align="middle" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
                    </object>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

src/IRY/AppliBundle/Resources/views/Application/debriefingStep.html.twig
{% extends 'IRYAppliBundle:Application:base.html.twig' %}

{% block header_title %}
    {{course.name}}
{% endblock %}

{% block header_back_btn %}
<a href="{{ path('iry_appli_dc', {course_id: course.id} ) }}" id="back_btn">
        <img src="{{ asset('bundles/iryappli') }}/img/fleche_gauche.png" alt="Retour accueil">
    </a>
{% endblock %}

{% block body %}
    <div id="content">
        <section id="dc">

        </section>
    </div>
{% endblock %}

src/IRY/AppliBundle/Resources/views/Application/exercicePratique.html.twig
{% extends 'IRYAppliBundle:Application:base.html.twig' %}

{% block header_title %}
    {{course.name}}
{% endblock %}

{% block header_back_btn %}
    <a href="{{ path('iry_appli_choixcours', {helicopter_id: course.subTheme.theme.helicopter.id}) }}" id="back_btn">
        <img src="{{ asset('bundles/iryappli') }}/img/fleche_gauche.png" alt="Retour accueil">
    </a>
{% endblock %}

{% block body %}
    <div id="content">
        <section id="ep">
            <div class="ep_wrap cf">
                <div class="list">
                    <ul class="pilot_list">
            			{% for pilot in pilots %}
                            <a href="{{ path("iry_appli_ep_pilot", {course_id: course.id, pilot_id: pilot.id}) }}">
                                
                                <li class="pilot" data-pilot-id="{{ pilot.id }}">
                                    <div class="pilot_name element">
                                        <span>{{pilot.name}}</span>
                                    </div>
                                    
                                    {% set currentStep = pilot.currentStep %}
                                    <div class="step element percent">
                                        <span class="bar percent-value" data-percent="{{ (currentStep is null) ? 0 : currentStep.percentInCourse}}"></span>
                                        <span class="title">
                                            {% if not currentStep is null %}
                                                {{ pilot.currentStep.name }}
                                            {% else %}
                                                Pilot has not started
                                            {% endif %}
                                        </span>
                                    </div>
                                    <div class="success element">
                                        <span>{{ pilot.nbSuccess }}</span>
                                    </div>
                                    <div class="errors element">
                                        <span>{{ pilot.nbErrors }}</span>
                                    </div>
                                    <div class="call element">
                                        <span {% if (pilot.isCalling == true) %}class="active"{% endif %} data-call-time="{{pilot.javascriptTimestampDateCalling}}"></span>
                                    </div>
                                </li>
                                
                            </a>
                        {% endfor %}
                    </ul>
                </div>
                <a href="{{ path('iry_appli_dc', {course_id: course.id}) }}" class="gotodebriefing"  data-step="8" data-intro="Lorsque l'exercice pratique est terminé, l'instructeur propose aux apprennats de débriefer autour de cet exercice (page en cours de developpement).">
                
                    Go to Debriefing
                </a>
            </div>
            <div class="ep_list_wrap">
                <div class="plus"></div>
                <h3>
                    {{course.name}}
                </h3>
                <div class="list">
                    <ul>
                        <li class="ep_step">
                            <div class="step element">
                                <span class="title"></span>
                            </div>
                            <div class="list_title element">
                                <span>Failures</span>
                            </div>
                        </li>
                        {% for step in course.steps %}
                            <li class="ep_step" data-step-id="{{ step.id }}">
                                <div class="step element">
                                    <span class="title">{{ step.name }}</span>
                                </div>
                                <div class="percent element">
                                    <span class="var percent-value" data-percent="{{step.getPercentNbLocalErrors}}"></span>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </section>
    </div>

    <script id="template-ep-pilot" type="x-tmpl-mustache">
        <a href="{{'{{pilotCenteredPath}}'}}">
            <li class="pilot" data-pilot-id="{{ '{{pilotId}}' }}">
                <div class="pilot_name element">
                    <span>{{ '{{pilotName}}' }}</span>
                </div>
                <div class="step element">
                    <span class="bar percent-value" data-percent="{{ '{{percentProgression}}' }}"></span>
                    <span class="title">{{ '{{stepName}}' }}</span>
                </div>
                <div class="success element">
                    <span>{{ '{{pilotSuccess}}' }}</span>
                </div>
                <div class="errors element">
                    <span>{{ '{{pilotErrors}}' }}</span>
                </div>
                <div class="call element">
                    <span {{ '{{callIsActive}}' }} data-call-time="{{ '{{callTime}}' }}"></span>
                </div>
            </li>
        </a>
    </script>
    <script>
        var checkPilotsUrl = "{{ path('get_pilots', { "_format" : "json" }) }}";
        var viewPilotUrl = "{{ path("iry_appli_ep_pilot", {course_id: course.id, pilot_id: "pilotId"}) }}";
    </script>
{% endblock %}

src/IRY/AppliBundle/Resources/views/Application/step.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Step</title>
</head>
<body>

    <table>
    	<tr>
    		<td>Course</td>
    	   	<td>Step</td>
    		<td>Failures</td>
    	</tr>
		<tr>
			<td><!--Nom cours-->
				{{course.name}}
			</td>

			<td><!--Liste des étapes-->
		        <ul>
			        {% for step in course.steps %}
		        		<li id="Step{{step.id}}">{{step.name}}</li>
			        {% endfor %}
		        </ul>
			</td>

			<td>
				{% for etape in course.steps %} <!-- nommée etape pour differencier -->
					{% set nbEssai = 0 %}
					{% set nbErrors = 0 %}
			        {% for resultat in etape.results %}  <!-- nommée resultat pour differencier -->
			        	{% set nbEssai = nbEssai + 1 %}
			        	{% if (resultat.isError == true) %}
			        		{% set nbErrors = nbErrors + 1 %}	
			        	{% endif%}
			        {% endfor %}
			        <li>{{nbErrors*nbEssai*5/20}}%</li>
			    {% endfor %} 
		        
			</td>
		</tr>
    </table>
</body>
</html>

src/IRY/AppliBundle/Resources/views/Application/videoImmersive.html.twig
{% extends 'IRYAppliBundle:Application:base.html.twig' %}

{% block header_title %}
    {{course.name}}
{% endblock %}

{% block header_back_btn %}
    <a href="{{ path('iry_appli_choixcours', {helicopter_id: course.subTheme.theme.helicopter.id}) }}" id="back_btn">
        <img src="{{ asset('bundles/iryappli') }}/img/fleche_gauche.png" alt="Retour accueil">
    </a>
{% endblock %}

{% block body %}
    <div id="content">
        <section id ="vi" class="cf">
            <div class="video_wrap">
{#                 {% if not course.immersiveMovie is null %}
                {{ include('IRYAppliBundle:ImmersiveApplication:blockUnityPlayer.html.twig', {'pathUnityFile' : '/'~course.immersiveMovie.unityPath}) }}
                {% endif %} #}

            {{ include('IRYAppliBundle:ImmersiveApplication:blockUnityPlayer.html.twig', {'pathUnityFile' : "/uploads/vi/ImmersiveVideo-Webplayer.unity3d"}) }}

            </div>
        </section>
        <section class="schema_image">
            <div class="schema_image_plus"></div>
            <div class="schema_image_wrap">
                <ul class="images">
                    {% for image in images %}
                        <li>
                            <span>{{image.name}}</span>
                            <img class="imgschema" src="/{{image.webPath}}" alt="{{image.name}}">
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </section>
    </div>
    <script>
       var imageUrl = "{{ path("iry_rest_send_image", {url: 0 }) }}";
    </script>
{% endblock %}